### ISSUE TITLE
구에에에에에엑

### ISSUE THREAD

**Issue by ajwwlswotjd** [ppch0305/yydh_graduation_album_page#1]
부에에에에에ㅔ에에에에에ㅔ에엥에ㅔ에에ㅔ에에ㅔ에엑
![a64a4d60470e8b2a02b2eb3cf99998ac](https://user-images.githubusercontent.com/51257601/98055346-9fc3f980-1e80-11eb-872b-1c4ed6fc03a4.png)

**Comment by ppch0305** [comment]
ㅎㅎ

**Comment by Jinu0107** [comment]
Good~
